alerts:
  - id: process-appeal-worbooks-not-run
    name: "Appeal workbooks not run"
    log_group: /ccao/jobs/appeal_workbooks
    log_query: "?total ?Total ?TOTAL"
    fail_if: "no_match"
    schedule: "0 12 * * 1-5"
    lookback_hours: 12
    aws_sns_topic: ccao-ic-vm-job-alarm
    failure_message: >-
      The daily writing of the appeal workbooks did not run.
      See the CloudWatch logs for details:
      https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Fccao$252Fjobs$252Fappeal_workbooks

  - id: process-appeal-workbooks-error
    name: "Appeal workbooks error"
    log_group: /ccao/jobs/appeal_workbooks
    log_query: "?error ?Error ?ERROR ?exception ?Exception ?EXCEPTION ?FAIL"
    fail_if: "match"
    schedule: "0 12 * * 1-5"
    lookback_hours: 12
    aws_sns_topic: ccao-ic-vm-job-alarm
    failure_message: >-
      The daily writing of the appeal workbooks encountered an unexpected
      error. See the CloudWatch logs for details:
      https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Fccao$252Fjobs$252Fappeal_workbooks
