alerts:
  - id: service-appeal-worbooks-not-run
    name: "Appeal Workbooks not run"
    log_group: /ccao/jobs/appeal_workbooks
    log_query: ""
    fail_if: "no_match"
    schedule: "0 12 * * *"
    lookback_hours: 12
    aws_sns_topic: ccao-cloudwatch-alarm
    failure_message: >-
      The nightly writing of the appeal workbooks did not run.
      See the CloudWatch logs for details:
      https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Fccao$252Fjobs$252Fappeal_workbooks
      
  - id: service-appeal-workbooks-error
    name: "Appeal Workbooks error"
    log_group: /ccao/jobs/appeal_workbooks
    log_query: "?error ?Error ?ERROR ?exception ?Exception ?EXCEPTION ?FAIL"
    fail_if: "match"
    schedule: "0 12 * * *"
    lookback_hours: 12
    aws_sns_topic: ccao-cloudwatch-alarm
    failure_message: >-
      The nightly writing of the appeal workbooks encountered an unexpected
      error. See the CloudWatch logs for details:
      https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Fccao$252Fjobs$252Fappeal_workbooks
