name: check-alerts

on:
  schedule:
    # Run every 3 hours (midnight, 3am, 6am, 9am, noon, 3pm, 6pm, 9pm UTC).
    # This window is deliberately wide because we have observed scheduled
    # workflows running up to 2 hours later than their scheduled time.
    # See README.md for details.
    #
    # This window must match the `CHECK_WINDOW_HOURS` and
    # `ALLOWED_SCHEDULE_HOURS`constants defined in the app code. If you update
    # this schedule, make sure to update those constants as well.
    - cron: "0 */3 * * *"
  workflow_dispatch:  # Allow manual runs for testing

# Configure a concurrency group so that only one instance of this workflow
# can run at a given time. If multiple instances want to run at the same time,
# _don't_ cancel the current run so as to allow it to complete the check and
# notification process. This config should hopefully never be necessary, since
# the underlying script is intended to run very quickly, but we set it out of
# an abundance of caution
concurrency:
  # Concurrency is enforced at the workflow level, meaning there can't ever be
  # multiple instances of this workflow running, even if one of the runs is on
  # a feature branch. This is appropriate because we don't currently have
  # staging environments for our alerts, so all workflows must run against prod,
  # regardless of whether they are running on the main branch
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  PYTHONUNBUFFERED: "1"
  UV_FROZEN: 1

jobs:
  check-alerts:
    runs-on: ubuntu-latest
    permissions:
      # Needed to interact with GitHub's OIDC Token endpoint so we can auth AWS
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          python-version: "3.14"

      - name: List config files
        id: list-configs
        shell: bash
        run: |
          # Configure bash to expand globs to null when they don't match
          # anything, rather than remain unexpanded. This allows us to
          # match on both .yml and .yaml file extensions, extracting the
          # output to an array while excluding any globs that don't match
          # anything
          shopt -s nullglob
          config_files=(config/*.yml config/*.yaml)
          echo "config_files=${config_files[*]}" >> "$GITHUB_OUTPUT"

      - name: Find due alerts
        id: find-due
        shell: bash
        run: |
          # In case of an error in the command that runs in the `due` command
          # substitution, exit with the status code of that command. This is
          # necessary since command substitution suppresses errors by default
          due=$(uv run python -m alerts.check ${{ steps.list-configs.outputs.config_files }} --dry-run) || exit $?
          if [[ -n "$due" ]]; then
            echo "Alerts due:"
            echo "$due"
            echo "alerts_due=true" >> "$GITHUB_OUTPUT"
          else
            echo "No alerts due."
            echo "alerts_due=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Mask sensitive identifiers from logs
        if: steps.find-due.outputs.alerts_due == 'true'
        shell: bash
        run: echo "::add-mask::${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Configure AWS credentials
        if: steps.find-due.outputs.alerts_due == 'true'
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          aws-region: us-east-1
          role-duration-seconds: 900

      - name: Run alert checks
        if: steps.find-due.outputs.alerts_due == 'true'
        id: run-checks
        shell: bash
        run: |
          results=$(uv run python -m alerts.check ${{ steps.list-configs.outputs.config_files }} --format json) || exit $?
          echo "Results:"
          echo "$results"
          echo "results=$results" >> "$GITHUB_OUTPUT"
          echo "check_failed=$(echo "$results" | jq -r '.any_failed')" >> "$GITHUB_OUTPUT"

      - name: Notify failed alerts
        if: steps.run-checks.outputs.check_failed == 'true'
        env:
          # Save run results to an env var. This has two benefits:
          #
          #   1. GitHub will handle escaping any special characters like quotes
          #      that might otherwise interfere with bash interpreting the
          #      command input
          #   2. GitHub will sanitize any untrusted input in the process of
          #      assigning it to an env var; this is not strictly necessary
          #      our case, since we expect to trust the input, but it's good
          #      universal practice per their docs:
          #      https://docs.github.com/en/actions/reference/security/secure-use#use-an-intermediate-environment-variable
          RESULTS: ${{ steps.run-checks.outputs.results }}
        shell: bash
        run: |
          uv run python -m alerts.notify \
            "$RESULTS" \
            --account-id ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Fail if any checks failed
        if: steps.run-checks.outputs.check_failed == 'true'
        run: exit 1
