name: check-alerts

on:
  schedule:
    # Run every 3 hours (midnight, 3am, 6am, 9am, noon, 3pm, 6pm, 9pm UTC).
    # This window is deliberately wide because we have observed scheduled
    # workflows running up to 2 hours later than their scheduled time.
    # See README.md for details.
    #
    # This window must match the `CHECK_WINDOW_HOURS` and
    # `ALLOWED_SCHEDULE_HOURS`constants defined in the app code. If you update
    # this schedule, make sure to update those constants as well.
    - cron: "0 */3 * * *"
  workflow_dispatch:  # Allow manual runs for testing
  pull_request:  # Enabled for testing; please delete

# Configure a concurrency group so that only one instance of this workflow
# can run at a given time. If multiple instances want to run at the same time,
# _don't_ cancel the current run so as to allow it to complete the check and
# notification process
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  PYTHONUNBUFFERED: "1"
  UV_FROZEN: 1

jobs:
  check-alerts:
    runs-on: ubuntu-latest
    permissions:
      # Needed to interact with GitHub's OIDC Token endpoint so we can auth AWS
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          python-version: "3.14"

      - name: List config files
        id: list-configs
        shell: bash
        run: |
          shopt -s nullglob
          config_files=(config/*.yml config/*.yaml)
          echo "config_files=${config_files[*]}" >> "$GITHUB_OUTPUT"

      - name: Find due alerts
        id: find-due
        shell: bash
        run: |
          # `|| exit $?` here catches any errors in the script call and raises
          # them, since otherwise the command substitution will suppress errors
          due=$(uv run python -m alerts.check ${{ steps.list-configs.outputs.config_files }} --dry-run) || exit $?
          if [[ -n "$due" ]]; then
            echo "Alerts due:"
            echo "$due"
            echo "alerts_due=true" >> "$GITHUB_OUTPUT"
          else
            echo "No alerts due."
            echo "alerts_due=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Mask sensitive identifiers from logs
        if: steps.find-due.outputs.alerts_due == 'true'
        shell: bash
        run: echo "::add-mask::${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Configure AWS credentials
        if: steps.find-due.outputs.alerts_due == 'true'
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          aws-region: us-east-1
          role-duration-seconds: 900

      - name: Run alert checks
        if: steps.find-due.outputs.alerts_due == 'true'
        id: run-checks
        shell: bash
        run: |
          results=$(uv run python -m alerts.check ${{ steps.list-configs.outputs.config_files }} --format json) || exit $?
          echo "Results:"
          echo "$results"
          echo "results=$results" >> "$GITHUB_OUTPUT"
          echo "check_failed=$(echo "$results" | jq -r '.any_failed')" >> "$GITHUB_OUTPUT"

      - name: Notify failed alerts
        if: steps.run-checks.outputs.check_failed == 'true'
        env:
          # Save run results to an env var. This has two benefits:
          #
          #   1. GitHub will handle escaping any special characters like quotes
          #      that might otherwise break parsing
          #   2. GitHub will sanitize any untrusted input; not a big deal in
          #      our case, since we expect to trust the input, but useful per
          #      their guidance nonetheless:
          #      https://docs.github.com/en/actions/reference/security/secure-use#use-an-intermediate-environment-variable
          RESULTS: ${{ steps.run-checks.outputs.results }}
        shell: bash
        run: |
          uv run python -m alerts.notify \
            "$RESULTS" \
            --account-id ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Fail if any checks failed
        if: steps.run-checks.outputs.check_failed == 'true'
        run: exit 1
