name: check-alerts

on:
  schedule:
    - cron: "0 * * * *"  # Run at the top of every hour
  workflow_dispatch:  # Allow manual runs for testing

env:
  PYTHONUNBUFFERED: "1"
  UV_FROZEN: 1

jobs:
  check-alerts:
    runs-on: ubuntu-latest
    permissions:
      # Needed to interact with GitHub's OIDC Token endpoint so we can auth AWS
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          python-version: "3.14"

      - name: Find due alerts
        id: find-due
        shell: bash
        run: |
          # `|| exit $?` here catches any errors in the script call and raises
          # them, since otherwise the command substitution will suppress errors
          due=$(uv run python scripts/check_alerts.py alerts/*.yml --dry-run) || exit $?
          if [[ -n "$due" ]]; then
            echo "Alerts due:"
            echo "$due"
            echo "alerts_due=true" >> "$GITHUB_OUTPUT"
          else
            echo "No alerts due."
            echo "alerts_due=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Mask sensitive identifiers from logs
        if: steps.find-due.outputs.alerts_due == 'true'
        shell: bash
        run: echo "::add-mask::${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Configure AWS credentials
        if: steps.find-due.outputs.alerts_due == 'true'
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          aws-region: us-east-1
          role-duration-seconds: 900

      - name: Run alert checks
        if: steps.find-due.outputs.alerts_due == 'true'
        shell: bash
        run: uv run python scripts/check_alerts.py alerts/*.yml
