name: test

on:
  pull_request:
  push:
    branches: [main]

env:
  PYTHONUNBUFFERED: "1"
  UV_FROZEN: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          python-version: "3.14"
          cache-suffix: pytest

      - name: Run Python tests
        shell: bash
        run: uv run --extra dev pytest
